import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Providers } from "./providers";
import {
  ClerkProvider,
} from '@clerk/nextjs'
import NavBar from "./components/navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "CycleMate",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <ClerkProvider>
      <html lang="en" className={`cycle-mate`}>
        <body>
          <NavBar />
          <Providers>
          {children}
          </ Providers>
        </body>
      </html>
    </ClerkProvider>
  )
}
